package Project.Common;

public enum PayloadType {
    CONNECT, DISCONNECT, MESSAGE, CLIENT_ID, RESET_USER_LIST, SYNC_CLIENT, 
    CREATE_ROOM, JOIN_ROOM, GET_ROOMS, MUTE_USER, UNMUTE_USER, LIST_ROOMS, ROLL,
    
}
